export const factions = new Array (
    'Adepta Sororitas',
    'Adeptus Custodes',
    'Adeptus Mechanicus',
    'Aeldari',
    'Astra Militarum',
    'Blood Angels',
    'Chaos Daemons',
    'Chaos Knights',
    'Chaos Space Marines',
    'Dark Angels',
    'Dark Eldars',
    'Dead Guard',
    'Genestealer Cults',
    'Grey Knights',
    'Harlequins',
    'Imperial Knights',
    'Inquisition',
    'Leagues of Votann',
    'Necrons',
    'Orks',
    'Space Marines',
    'Space Wolves',
    'Tau',
    'Thousand Sons',
    'Tyranids'
)